# Generated by Django 4.2.7 on 2023-11-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_category_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
